// src/components/form/Input.vue
<template>
    <input
      :type="typeName"
      :placeholder="placeholderName"
      :id="idName"
      :value="valueName"
      @input="$emit('input', $event.target.value)"
      :required="isRequired"
      class="form__input"
      :autocomplete="autocompleteName"
    />
</template>

<script>
export default {
  name: 'FormInput',
  props: ['typeName', 'placeholderName', 'valueName', 'idName', 'isRequired', 'autocompleteName']
}
</script>

// src/components/form/Input.jsx
import React from 'react'

export const FormInput = props => {
  return (
    <input
      type={props.typeName}
      value={props.valueName}
      onChange={props.onChangeName}
      placeholder={props.placeholderName}
      className='form__input'
      id={props.idName}
    />
  )
}
