// src/layout/Footer/index.tsx
import React from 'react'
import styled from 'styled-components'

const FooterStyles = styled.footer`
  @media (max-width: 949px) {
    flex-direction: column;
    justify-content: center;
  }
  @media (min-width: 950px) {
    flex-direction: row;
  }
  display: flex;
  align-items: center;
  background-color: white;
  border-top: 1px solid rgba(0, 0, 0, 0.27);
  padding: 10px 20px;
  margin-top: 50px;
  .title {
    @media (min-width: 950px) {
      flex: 1;
      padding: 2.5px 5px;
    }
    font-size: 2.05em;
    font-weight: 300;
    .link {
      text-decoration: none;
      color: inherit;
    }
  }
  .copyright {
    @media (max-width: 949px) {
      font-size: 0.985em;
      padding: 10px 20px;
    }
    @media (min-width: 950px) {
      font-size: 1.2em;
      padding: 2.5px 5px;
      text-align: right;
    }
  }
`

const Footer = () => (
  <FooterStyles>
    <h1 className="title">
      <a href="/" className="link">
        Cass Theatre
      </a>
    </h1>
    <small className="copyright">
      &copy; Cass Theatre {new Date().getFullYear()}
    </small>
  </FooterStyles>
)

export default Footer

// src/components/global/Footer.vue
<template>
    <footer class="global__footer">
      <p class="global__footer__title">
        <router-link to="/">
          Cass Theatre
        </router-link>
      </p>
      <small class="global__footer__copyright">
        &copy; Cass Theatre {{year}}
      </small>
    </footer>
</template>

<script>
export default {
  name: 'GlobalFooter',
  computed: {
    year () {
      return new Date().getFullYear()
    }
  }
}
</script>

<style lang="scss">
@import '@/styles/-media-queries';

.global__footer {
  background-color: var(--color-brand);
  box-shadow: 1px 1px 5px #0000009c;
  display: flex;
  flex-direction: column;
  align-items: center;
  z-index: 1000;
  width: 100%;
  & .global__footer__title {
    color: var(--color-text-light);
    font-weight: var(--font-weight);
    @media (--viewport-mobile) {
      font-size: 2.15em;
    }
    @media (--viewport-desktop) {
      font-size: 2.65em;
    }
    a {
      text-decoration: none;
      color: inherit;
    }
  }
  & .global__footer__copyright {
    color: var(--color-text-light);
    margin: 10px 0px;
     @media (--viewport-mobile) {
      font-size: 1.15em;
    }
    @media (--viewport-desktop) {
      font-size: 1.65em;
    }
  }
}

</style>
