// src/layout/Footer/index.jsx
import React from 'react'
import './styles.scss'

const Footer = () => (
  <footer className="footer">
    <h1 className="title">
      <a href="/" className="link">
        Cass Theatre
      </a>
    </h1>
    <small className="copyright">
      &copy; Cass Theatre {new Date().getFullYear()}
    </small>
  </footer>
)

export default Footer

// src/components/global/Footer.vue
<template>
    <footer class="global__footer">
      <p class="global__footer__title">
        <router-link to="/">
          Cass Theatre
        </router-link>
      </p>
      <small class="global__footer__copyright">
        &copy; Cass Theatre {{year}}
      </small>
    </footer>
</template>

<script>
export default {
  name: 'GlobalFooter',
  computed: {
    year () {
      return new Date().getFullYear()
    }
  }
}
</script>
