// src/layout/Header/index.tsx
import React from 'react'
import styled from 'styled-components'

const HeaderStyles = styled.header`
  position: sticky;
  top: 0;
  padding: 10px 20px;
  border-bottom: 1.5px solid hsla(0, 0%, 50.2%, 0.253);
  background-color: white;
  z-index: 100000;
  .title {
    text-align: center;
    font-weight: 300;
    font-size: 2.05em;
    transition: all 0.35s;
    &:hover {
      letter-spacing: 0.15em;
    }
    .link {
      text-decoration: none;
      color: inherit;
    }
  }
`

const Header = () => (
  <HeaderStyles className="header">
    <h1 className="title">
      <a href="/" className="link">
        Cass Theatre
      </a>
    </h1>
  </HeaderStyles>
)

export default Header

// src/components/global/Header.vue
<template>
  <header class="global__header">
    <h1 class="global__header__title">
      <router-link to="/">Cass Theatre</router-link>
    </h1>
  </header>
</template>

<script>
export default {
  name: 'GlobalHeader'
}
</script>

<style lang="scss">
@import '@/styles/-media-queries';

.global__header {
  background-color: var(--color-brand);
  box-shadow: 1px 1px 5px #0000009c;
  display: flex;
  flex-direction: row;
  justify-content: center;
  position: fixed;
  z-index: 1000;
  width: 100%;
  top: 0;
  & .global__header__title {
    color: var(--color-text-light);
    font-weight: var(--font-weight);
    @media (--viewport-mobile) {
      font-size: 2.15em;
    }
    @media (--viewport-desktop) {
      font-size: 2.65em;
    }
    & a {
      text-decoration: none;
      color: inherit;
    }
  }
}
</style>
